# path of config files.  Use the object-name must equal to folder name for the config
config-path: "/Users/bruceadmin/CodeBase/kubernetes-objects/"

# Define kubernetes objects
# - object-name:
objects:
  - "go-example"
  
